Assets/Scenes/Douglas.Scene.unity
Assets/Scenes/Douglas.Scene.unity.meta
ProjectSettings/SceneTemplateSettings.json

i have no idea if this is right

lab 1 i guess

---

Assets/Scenes/AndrewsPlayground.unity
Assets/Scenes/AndrewsPlayground.unity.meta

beep boop new scene just dropped

Setup for my Play Scene

---

Assets/Development/Scripts/Player/States/Player/PlayerGroundState.cs
Assets/Development/Scripts/Player/States/Player/PlayerStateMachine.cs
Assets/Development/Scripts/Player/States/Player/PlayerThrowState.cs
Assets/Development/Scripts/Player/States/StateMachine.cs
Assets/Scenes/WhiteBox.unity

Dash not going thru walls anymore
player interaction with fridge fixed

Dash and pick up bugs fixed

---

Assets/Development/Scripts/Camera/UiCameraManager.cs
Assets/Scenes/Main Menu Scene.unity

visuals enabling and disabling menus

Updated Main menu

---

Assets/Development/Scripts/UI/DisplayAttributes.cs

Bug appeared from merge, deleted one line from displayattributes.cs where order attributes appeared on customer canvas prefab

Removed extra order prefab bug

---

Assets/Development/Prefabs/Customers/Customer Sample.prefab
Assets/Development/Prefabs/UI/OrderUiPrefab.prefab
Assets/Development/Scripts/AI/CustomerBase.cs
Assets/Development/Scripts/AI/CustomerManager.cs
Assets/Development/Scripts/UI/DisplayAttributes.cs
Assets/Development/Scripts/UI/OrderStats.cs
Assets/Scenes/Michael Scene.unity

Customer names in code but not sure where to display in UI yet
Customer numbers appear in Order UI
Customer numbers appear over customer heads when ordering and afterward

Added customer names and number indicators

---

Assets/Development/Prefabs/Customers/Customer Sample.prefab
Assets/Development/Prefabs/UI/HUD.prefab
Assets/Development/Prefabs/UI/OrderAttributes.prefab
Assets/Development/Prefabs/UI/OrderUiPrefab.prefab
Assets/Development/Prefabs/UI/Star.prefab
Assets/Development/Prefabs/UI/Star.prefab.meta
Assets/Development/Scripts/AI/CustomerBase.cs
Assets/Development/Scripts/AI/CustomerReview.cs
Assets/Development/Scripts/AI/CustomerReview.cs.meta
Assets/Development/Scripts/Managers/UIManager.cs
Assets/Development/Scripts/UI/DisplayAttributes.cs
Assets/Development/Scripts/UI/OrderStats.cs
Assets/Scenes/Michael Scene.unity
Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF.asset

- Customer review framework (finish when moods and garbage is implemented.  Garbage and mood have fake values  for now
- RemoveCustomerOrderUI() was not implemented, oops
- Customer name and number now only face the camera instead of spinning with the customer
- Added a gameplay tips HUD item just in case
- Adjusted the score and timer positions

Customer reviews and bug fixes

---

Assets/Development/Scripts/Stations/BrewingStation.cs

Minigame now properly disappears after interacting with it

---

Assets/Art/Materials/floor/Materials/FabricVelvetEmbossed025_COL_4K_METALNESS 1.mat
Assets/Art/Materials/floor/Materials/FabricVelvetEmbossed025_COL_4K_METALNESS 1.mat.meta
Assets/Art/Materials/floor/Materials/GroundForest003_COL_VAR1_6K.mat
Assets/Art/Materials/floor/Materials/GroundForest003_COL_VAR1_6K.mat.meta
Assets/Development/Scripts/Multiplayer/PlayerConfigurationManager.cs
Assets/Scenes/Main Menu Scene.unity
Assets/Scenes/WhiteBox.unity
ProjectSettings/Packages/com.unity.probuilder/Settings.json

https://
- - Players can only join after clicking on start button (still need mor work, but good for now)
- Customer disappearing bug detected, removed some tables that are conflicting with customer distance to leave (to be resolved in the new level layout)
- Added some temporary furniture in place of the tables
-

Main Menu and Whitebox Polish

---

Assets/Development/Scripts/AI/CustomerBase.cs
Assets/Development/Scripts/AI/CustomerReview.cs
Assets/Development/Scripts/Managers/ScoreTimerManager.cs
Assets/Development/Scripts/Managers/UIManager.cs

https://trello.com/c/sMKJy8j6
- When counter reaches zero in builds the game keeps going.  There was a bug in the score count that returned an null reference
- None

Fixed timer countdown bug

---

Assets/Development/Scripts/AI/CustomerBarFloor.cs
Assets/Development/Scripts/AI/CustomerBarFloor.cs.meta
Assets/Development/Scripts/AI/CustomerLineQueuing.cs
Assets/Development/Scripts/AI/CustomerManager.cs
Assets/Development/Scripts/AI/CustomerReview.cs

https://
- Added CustomerBarFloor.cs
Change cafe crowd to get line queue + total floor people
- added 2 methods to encapsulate total customer numbers
Encapsulate Variables on CustomerManager.cs
- Need to pull before fixing other stuff first

Customer Floor Fixes

---

Assets/Development/Audio.meta
Assets/Development/Audio/Audio Mixer.meta
Assets/Development/Audio/Audio Mixer/VolumeSettings.mixer
Assets/Development/Audio/Audio Mixer/VolumeSettings.mixer.meta
Assets/Development/Audio/AudioScripts.meta
Assets/Development/Audio/AudioScripts/VolumeSettings.cs
Assets/Development/Audio/AudioScripts/VolumeSettings.cs.meta
Assets/Scenes/Main Menu Scene.unity

Added main menu audio control. 2 Sliders for music and SFX that work separately. Will add to in game settings soon.
https://
- 
-

Audio Settings

---

Assets/Development/Prefabs/UI/OrderUiPrefab.prefab
Assets/Development/Scripts/Managers/ScoreTimerManager.cs
Assets/Development/Scripts/Managers/UIManager.cs
Assets/Scenes/GameLoopScenes/TestScene.unity

https://
https://trello.com/c/vEJIfdYU/78-bug-reset-everything-when-going-to-main-menu-orders-timers-etc
- timer, ordres and score now disappear when returning to main menu
- timer and score reset when game restarts
-

Bugfix timerissues

---

Assets/Development/Prefabs/UI/DebugConsole.cs
Assets/Development/Prefabs/UI/DebugConsole.cs.meta
Assets/Development/Prefabs/UI/HUD.prefab
Assets/Development/Prefabs/UI/OrderAttributes.prefab
Assets/Development/Prefabs/UI/OrderUiPrefab.prefab
Assets/Development/Scripts/AI/CustomerBase.cs
Assets/Development/Scripts/AI/CustomerManager.cs
Assets/Development/Scripts/Managers/InputManager.cs
Assets/Development/Scripts/Managers/UIManager.cs
Assets/Development/Scripts/Player/ControllerInputs.cs
Assets/Development/Scripts/Player/ControllerInputs.inputactions
Assets/Development/Scripts/Player/States/Player/PlayerController.cs
Assets/Scenes/TestScenes/JuanTestScene.unity

[https://trello.com/c/FtLxyeid/91-feature-debug-console](https://trello.com/c/FtLxyeid/91-feature-debug-console) 
[https://trello.com/c/G64nEF3M/167-bug-grabingedientfromfloor-is-spelled-wrong](https://trello.com/c/G64nEF3M/167-bug-grabingedientfromfloor-is-spelled-wrong)
- Spelling mistake on GrabIngedientFromFloor()
- Activate Debug / Cheat console with ` (back tick)
Commands:
coffee # # # # # (drink attribute numbers)
order (all customers in line submit orders)
leave (all customers leave)

Debug / Cheat Console

---

Assets/Development/Scripts/Managers/InputManager.cs
Assets/Scenes/TestScenes/JuanTestScene.unity

https://
- Added controller dead zone for sensitivity
- increased player capsule collider for better interaction with stations
- 
-

Added controller dead zone for sensitivity

---

Assets/Development/Scripts/Managers/GameManager.cs
Assets/Scenes/GameLoopScenes/Main Menu Scene.unity

Difficult settings

---

Assets/Development/Prefabs/CustomerManager.prefab
Assets/Development/Prefabs/Player.prefab
Assets/Development/Prefabs/UI/DebugConsole.cs
Assets/Development/Scripts/AI/CustomerBarFloor.cs
Assets/Development/Scripts/AI/CustomerBase.cs
Assets/Development/Scripts/AI/CustomerManager.cs
Assets/Development/Scripts/Helpers/UIDebug.cs
Assets/Development/Scripts/Helpers/UIDebug.cs.meta
Assets/Development/Scripts/Managers/GameManager.cs
Assets/Development/Scripts/Player/States/Player/PlayerController.cs
Assets/Scenes/GameLoopScenes/NetworkScene.unity
Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF.asset

Networking

---

Assets/Scenes/MasterScenes/LobbyScene.unity
Assets/Scenes/MasterScenes/LobbyScene.unity.meta

Lobby Scene with UI menus, Using panels
https://
- Added UI to Lobby
-

Created Lobby Scene

---

Assets/Development/Prefabs/UI/HUD.prefab
Assets/Development/Scripts/Helpers/Managers/GameManager.cs
Assets/Development/Scripts/Player/PlayerController.cs
Assets/Development/Scripts/UI/GamePauseUI.cs
Assets/Development/Scripts/UI/HostDisconnectUI.cs
Assets/Development/Scripts/UI/HostDisconnectUI.cs.meta

https://
- Scrips to handle player and host disconnects
-

Disconnects

---

Assets/Development/Prefabs/Player/Player.prefab
Assets/Development/Scripts/Multiplayer/Network/ClientNetworkAnimator.cs
Assets/Development/Scripts/Multiplayer/Network/ClientNetworkAnimator.cs.meta

Clients can now see each other's animations
https://trello.com/c/7MDdoYGo/239-networking-go-no-go-decision
- Created a script called ClientNetworkAnimator which derives from NetworkAnimator but allows the owner of a player (Client) to show Animations to the other
-

Animations show between clients

---

Assets/Art/Imports (TO BE DELETED)/Mixamo/left strafe.fbx.meta
Assets/Art/Imports (TO BE DELETED)/Mixamo/right strafe.fbx.meta
Assets/Art/Imports (TO BE DELETED)/Mixamo/walking.fbx.meta

Fixed the baked in root transform positions

---

Assets/Scenes/MasterScenes/T5M3_BUILD.unity

Added missing references to gamescene

---

Assets/Development/Scripts/Helpers/Managers/GameManager.cs
Assets/Development/Scripts/Multiplayer/Network/TestingNetcodeUI.cs

Customers spawn after countdown

---

Assets/Scenes/MasterScenes/T5M3_BUILD.unity

Added missing customer reference to gamemanager

---

Assets/Scenes/MasterScenes/T5M3_BUILD.unity

Pause Menu Fix

---

Assets/Development/Prefabs/Customers/Customer Sample.prefab
Assets/Development/Scripts/AI/CustomerBase.cs
Assets/Development/Scripts/AI/CustomerReactionIndicator.cs
Assets/Development/Scripts/AI/CustomerReactionIndicator.cs.meta
Assets/Dreamteck.meta
Assets/Dreamteck/Splines.meta
Assets/Dreamteck/Splines/Examples.unitypackage.meta
Assets/Dreamteck/Splines/PlaymakerActions.unitypackage.meta
Assets/Dreamteck/Splines/TMPro.unitypackage.meta

https://
- 
- 
it sucks but it works

Customer reaction indicators Douglas

---

Assets/Development/Scripts/AI/Base.cs
Assets/Dreamteck/Splines/Examples.unitypackage.meta
Assets/Dreamteck/Splines/PlaymakerActions.unitypackage.meta
Assets/Dreamteck/Splines/TMPro.unitypackage.meta
Assets/Scenes/MasterScenes/T5M3_BUILD.unity

Can hand coffee to customer

---

Assets/Development/Scripts/Camera/UiCameraManager.cs
Assets/Scenes/MasterScenes/MainMenuScene.unity
ProjectSettings/EditorBuildSettings.asset

Main menu loads lobby
https://
- Main menu loads lobby
-

Main Menu To lobby

---

Assets/Art/Imports (TO BE DELETED)/JukeBox/Radio.prefab
Assets/Development/Scripts/Environment/Stations/RadioStation.cs
Assets/Scenes/MasterScenes/T5M3_BUILD.unity

https://
- Radio Network sync
-

Radio Network sync

---

Assets/Development/Prefabs/Stations/Sink.prefab
Assets/Scenes/MasterScenes/T5M3_BUILD.unity

Sink Sinching

---

Assets/Art/Skybox.meta
Assets/Scenes/MasterScenes/T5M3_BUILD.unity

https://trello.com/c/JrVy4nTx/381-make-a-basic-space-skybox
- Nothing fancy, just a particle effect with a sphere emitting for a really long time
- Changed virtual camera from skybox to "solid color" (black)

Simple space "skybox"

---

Assets/Scenes/MasterScenes/T5M3_BUILD.unity

A cube was placed in the middle of the scene on accident.  It was hidden by "Host disconnected" UI.  Just removing the cube.

Accidental cube placed in middle of scene

---

Assets/Development/Prefabs/Stations/Stations With UI Sliders/BeanStation.prefab
Assets/Development/Prefabs/Stations/Stations With UI Sliders/BioMatterStation.prefab
Assets/Development/Prefabs/Stations/Stations With UI Sliders/LiquidStation.prefab
Assets/Development/Prefabs/Stations/Stations With UI Sliders/SweetenerStation.prefab
Assets/Development/Scripts/UI/IngredientSelectionUI.cs
Assets/Scenes/MasterScenes/T5M3_BUILD.unity

https://trello.com/c/JrVy4nTx/381-make-a-basic-space-skybox
https://trello.com/c/cXxU22Sn/338-update-ingredient-stations-to-new-minimal-ui-element
https://trello.com/c/n3OFLYqD/317-lock-the-player-when-interacting-with-stations
- Dpad input on ingredient UI pop-up
- Fixed missing particle effect for silly space "skybox"
- Cleaned-up, recentered, removed dead objects from ingredient stations
- None

Gamepad input on ingredient stations, prefab cleanup, space particle effect

---

Assets/Development/Scripts/Helpers/Managers/GameManager.cs
Assets/Development/Scripts/Player/PlayerController.cs
Assets/Dreamteck.meta
Assets/Dreamteck/Splines.meta
Assets/Scenes/MasterScenes/LobbyScene.unity
Assets/Scenes/MasterScenes/T5M3_BUILD.unity
ProjectSettings/TagManager.asset

Reverts mikestiers/Baristapocalypse#147

Revert "New camera Douglas"

---

Assets/Development/Scripts/Environment/Stations/BrewingStation.cs
Assets/Development/Scripts/Player/PlayerController.cs

Deleted duplicated functions

---

Assets/Development/Scripts/Environment/Stations/TrashStation.cs

Properly updates player held items list when using trash

---

Assets/Scenes/MasterScenes/T5M3_BUILD.unity

Turn UI on again

---

Assets/Development/Scripts/Player/PlayerController.cs
Assets/Scenes/MasterScenes/T5M3_BUILD.unity

Cam v8.0000000

---

Assets/Development/Prefabs/Customers/Customer Sample.prefab
Assets/Development/Scripts/Helpers/Managers/GameManager.cs

Changing wait time because it's a bit too hard to hit 60 seconds with accuracy for demo purposes
NA
- Customer Sample prefab/customerWaitTime value change
- NA

CustomerWaitTime from 60 to 180

---

Assets/Development/Scripts/Helpers/Managers/GameManager.cs
Assets/Development/Scripts/Helpers/Managers/UIManager.cs
Assets/Scenes/MasterScenes/T5M3_BUILD.unity

- Time in game manager
- on game over go to main menu
https://
- 
-

last minute minor updated

---

Assets/Development/Scripts/Player/PlayerController.cs

Throw Error Fix

---

Assets/Development/Prefabs/Customers/Customer Sample.prefab

(https://trello.com/c/KAg5h5ZV)
(https://trello.com/c/YPIA7kYo)
- Added Customer Patience/WaitTime in difficultySO
- Removed the NavmeshWarning when instantiating customer
- Fixed Corner where player can squeeze through

Found a rogue Agent in customer prefab & Added Customer Patience/Wait Time

---

Assets/Development/Scripts/Player/PlayerController.cs

https://
- 1 second cooldown on dash, exposed in inspector for tweaking
-

Added Dash cooldown

---

Assets/Development/Scripts/Player/PlayerController.cs

https://
- Mouse cursor hides when using gamepad and shows when moving mouse again
-

Added HandleCursorVisibility.cs

---

Assets/Development/Scripts/AI/CustomerBase.cs
Assets/Development/Scripts/AI/CustomerManager.cs
Assets/Development/Scripts/Camera/MainMenuManager.cs
Assets/Development/Scripts/Helpers/GameValueHolder.cs
Assets/Development/Scripts/Helpers/GameValueHolder.cs.meta
Assets/Development/Scripts/Helpers/Managers/GameManager.cs
Assets/Scenes/MasterScenes/MainMenuScene.unity
Assets/Scenes/MasterScenes/T5M3_BUILD.unity

[https://](https://trello.com/c/oCREorJg)
- Migrated the DifficultySettings into the GameManager
- Implemented the difficulty buttons to adjust the difficulty
- If testing mode dont pick any difficulty

Feature/difficulty setting in main menu&game manager

---

Assets/Development/Scripts/Player/PlayerController.cs

https://
- Host cannot longer move players in the lobby scene
-

LockLobbyPlayerMove

---

Assets/Development/Scripts/AI/CustomerBase.cs
Assets/Development/Scripts/AI/CustomerManager.cs

https://
- Quick Fix for loitering
- Added Initial Customer Spawning
-

Added Initial Spawn and Fix logic for loiter

---

Assets/Development/Prefabs/UI/OrderStats.prefab
Assets/Development/Scripts/Environment/Stations/BrewingStation.cs
Assets/Development/Scripts/Helpers/Managers/DifficultySO.cs
Assets/Development/Scripts/Helpers/Managers/DifficultySettings.cs
Assets/Development/Scripts/UI/OrderStats.cs
Assets/Development/Scripts/UI/OrderStatsSegments.cs

https://trello.com/c/7y38z0qd/421-prepare-different-brewing-mechanics-for-testing-on-friday
- Brewing mechanic for what could be medium difficulty (3 target range)
- Cleaned up some UI bugs
- Added drinkthreshold to the difficulty scriptable object
- Difficulty setting reference is not explicitly used yet.  Hardcoded threshold at 3 for now so people can try before difficulty settings menu is hooked up this week

Possible medium difficulty mode

---

Assets/Development/Scripts/Helpers/Managers/UIManager.cs
Assets/Development/Scripts/Helpers/SceneHelper.cs
Assets/Development/Scripts/Helpers/SceneHelper.cs.meta
Assets/Development/Scripts/Helpers/Singleton.cs
Assets/Scenes/MasterScenes/MainMenuScene.unity

https://
- Created SceneHelper.cs to reset game loop and network
- This changes are only working on game over for the moment
-

Game loop reset

---

Assets/Development/Scripts/AI/CustomerManager.cs

Quick FIx missing 1 line for Initial Customer Spawn

---

Assets/Development/Scripts/Helpers/Managers/GameManager.cs
Assets/Development/Scripts/Helpers/SceneHelper.cs
Assets/Development/Scripts/Multiplayer/Network/BaristapocalypseMultiplayer.cs
Assets/Development/Scripts/Player/CharacterColorSelectUI.cs
Assets/Development/Scripts/UI/HostDisconnectUI.cs

https://
- Fix Bug when clients disconnected
-

Game loop update

---

Assets/Development/Prefabs/Player/Player.prefab
Assets/Development/Scripts/Player/PlayerController.cs

https://
- Stations distance update
- Customer Interaction tweak
-

Customer interaction touch up

---

Assets/Development/Scripts/Player/PlayerController.cs

https://
- tweak interaction distances 
-

Player/Customer Interaction

---

Assets/Development/Prefabs/Particles.meta
Assets/Development/Prefabs/Particles/ParticleTest.prefab
Assets/Development/Prefabs/Particles/ParticleTest.prefab.meta
Assets/Development/ScriptableObjects/ParticleSO.meta
Assets/Development/ScriptableObjects/ParticleSO/ParticleListSO.asset
Assets/Development/ScriptableObjects/ParticleSO/ParticleListSO.asset.meta
Assets/Development/ScriptableObjects/ParticleSO/ParticleTest.asset
Assets/Development/ScriptableObjects/ParticleSO/ParticleTest.asset.meta
Assets/Development/Scripts/Environment/Particles.meta
Assets/Development/Scripts/Environment/Particles/Particle.cs
Assets/Development/Scripts/Environment/Particles/Particle.cs.meta
Assets/Development/Scripts/Environment/Particles/ParticleListSO.cs
Assets/Development/Scripts/Environment/Particles/ParticleListSO.cs.meta
Assets/Development/Scripts/Environment/Particles/ParticleSO.cs
Assets/Development/Scripts/Environment/Particles/ParticleSO.cs.meta
Assets/Development/Scripts/Helpers/Interfaces/IparticleParent.cs
Assets/Development/Scripts/Helpers/Interfaces/IparticleParent.cs.meta
Assets/Development/Scripts/Multiplayer/Network/BaristapocalypseMultiplayer.cs

https://
- Particle Networking Implementation
- Added Particle.cs
- Added IparticleParent.cs
- Added ParticleSO
- Added ParticleListSO
-

Particle Networking Implementation

---

Assets/Development/Prefabs/Customers/Customer Sample.prefab

- customer review prefab reference was not set for some reason

customer review prefab unassigned

---

Assets/Scenes/MasterScenes/T5M3_BUILD.unity

-Stuff for CustomerReview
https://
- 
-

Fix for Scene stuff missing

---

Assets/Development/Scripts/AI/CustomerManager.cs

[https://](https://trello.com/c/g8rkshRL)
- 
-

Fix for Initial Customer Spawn

---

Assets/Scenes/MasterScenes/T5M3_BUILD.unity

Fixes Post Merge

---

Assets/Development/Scripts/AI/CustomerBase.cs
Assets/Development/Scripts/AI/CustomerManager.cs
Assets/Development/Scripts/Helpers/Managers/DifficultySettings.cs
Assets/Development/Scripts/Player/PlayerController.cs
Assets/Development/Scripts/UI/ShiftEvaluationUI.cs

Post Playtest Fixes

---

Assets/Development/Prefabs/UI/OrderStats.prefab
Assets/Development/Scripts/UI/OrderStats.cs
Assets/Scenes/MasterScenes/T5M3_BUILD.unity

https://trello.com/c/qgJpWEic/476-customer-timers-suspiciously-dont-work-sometimes
- Fixed ingredient updates not happening on first order
- Fixed ordertimer not moving
NA

Brewing stats bugs from refactor

---

Assets/Development/ScriptableObjects/EventsSO/GravityStormSO.asset
Assets/Development/Scripts/Environment/Events/RandomEventSO.cs
Assets/Development/Scripts/Helpers/Managers/GameManager.cs
Assets/Scenes/MasterScenes/T5M3_BUILD.unity

https://
- Refactor randomizer
- Added difficulties setting for random events
-

Event randomizer

---

Assets/Development/Scripts/UI/IngredientSelectionUI.cs

https://trello.com/c/JJKCEpdJ/444-network-sync-ingredients-stations-ui
- 
-

Feature/ingredient UI network

---

Assets/Development/Scripts/Helpers/Managers/GameManager.cs

https://trello.com/c/93a2MVYJ/237-consider-frame-rate-cap
- 
-

Set target frame rate to 60fps

---

Assets/Development/Scripts/UI/OrderStats.cs

NA
- Medium diff mode orderstats were calculated wrong
- Forgiveness plz

Medium mode broken

---

.idea/.idea.Baristapocalypse/.idea/workspace.xml
Assets/Development/Scripts/Environment/Messes/Spill.cs
Assets/Development/Scripts/Player/PlayerController.cs
Assets/Scenes/MasterScenes/T5M3_BUILD.unity

spill now can be cleaned up

---

Assets/Scenes/MasterScenes/T5M3_BUILD.unity

Fixing Bad Pointers

---

Assets/Development/Scripts/Helpers/Managers/SoundManager.cs
Assets/Development/Scripts/UI/CustomerReviewManager.cs

https://
- SoundManager.cs fix for SFX not put in a mixer group
- fix for CustomerReviewManager.cs not outputting a review after the first
-

Fixes to SFX and Customer Review

---

Assets/Development/Prefabs/Customers/Customer Sample.prefab
Assets/Development/Scripts/Helpers/Managers/DifficultySettings.cs
Assets/Development/Scripts/Helpers/Managers/GameManager.cs

https://
- Just some FollowUp Fixes from recent Previous PRs
-

Quick Fixes

---

Assets/Development/Prefabs/Customers/Customer Sample.prefab
Assets/Development/Scripts/Helpers/Managers/DifficultySettings.cs
Assets/Development/Scripts/Helpers/Managers/GameManager.cs

Reverts mikestiers/Baristapocalypse#263

Revert "Quick Fixes"

---

Assets/Development/Scripts/Camera/MainMenuManager.cs
Assets/Development/Scripts/Helpers/Managers/DifficultySettings.cs
Assets/Development/Scripts/Helpers/Managers/GameManager.cs
Assets/Development/Scripts/Multiplayer/Network/BaristapocalypseMultiplayer.cs
Assets/Development/Scripts/UI/IngredientSelectionUI.cs
Assets/Scenes/MasterScenes/MainMenuScene.unity
Assets/Scenes/MasterScenes/T5M3_BUILD.unity

Reverts mikestiers/Baristapocalypse#262

Revert "Fix/game manager"

---

Assets/Development/Scripts/Camera/MainMenuManager.cs
Assets/Development/Scripts/Helpers/Managers/UIManager.cs
Assets/Scenes/MasterScenes/T5M3_BUILD.unity

game manager Fix

---

Assets/Development/Scripts/Player/PlayerController.cs

https://
- Change Force mode from acceleration to Impulse, so the player can have the dash impulse even when there is no input
-

Dash Tweak

---

Assets/Development/Scripts/AI/CustomerBase.cs
Assets/Development/Scripts/AI/CustomerManager.cs
Assets/Development/Scripts/AI/CustomerRandomizer.cs
Assets/Development/Scripts/Camera/MainMenuManager.cs
Assets/Development/Scripts/Helpers/GameValueHolder.cs
Assets/Development/Scripts/Helpers/Managers/DifficultySettings.cs
Assets/Development/Scripts/Helpers/Managers/GameManager.cs
Assets/Development/Scripts/Helpers/SceneHelper.cs
Assets/Development/Scripts/Multiplayer/Network/BaristapocalypseMultiplayer.cs
Assets/Development/Scripts/UI/GameOverUI.cs
Assets/Development/Scripts/UI/IngredientSelectionUI.cs
Assets/Development/Scripts/UI/OrderStats.cs
Assets/Scenes/MasterScenes/MainMenuScene.unity

https://trello.com/c/tArK5CP7
- Game Manager causes so many bugs to move to mainmenu scene that we opted to just make a new script
-

DifficultySettings is now in GameValueHolder

---

Assets/Development/Prefabs/Ingredients/CoffeeCup.prefab
Assets/Development/Scripts/Player/PlayerController.cs

https://
- Coffee Cup now falls to the floor when player throws
-

Coffee Cup now falls to the floor when player throws

---

Assets/Development/Scripts/Helpers/Managers/TutorialManager.cs

Quick fix to remove null reference, needs to be fixed for tutorial

---

Assets/Development/Scripts/Camera/CameraLookAt.cs
Assets/Development/Scripts/Camera/CameraLookAt.cs.meta
Assets/Development/Scripts/Camera/CameraMove.cs
Assets/Development/Scripts/Camera/CameraMove.cs.meta
Assets/Scenes/MasterScenes/T5M3_BUILD.unity

Cameras douglas first and secound camera made

---

.idea/.idea.Baristapocalypse/.idea/workspace.xml
Assets/Development/Scripts/Player/PlayerController.cs

added a tag to CoffeeCup
changed GetIngredientSO tag check from Milk to CoffeeCup
https://
- 
-

fixed spill

---

Assets/Art/Materials/Glow.mat
Assets/Art/Materials/Glow.mat.meta
Assets/Development/Animations/GravityLights.meta
Assets/Development/Animations/GravityLights/FlashingLights.anim
Assets/Development/Animations/GravityLights/FlashingLights.anim.meta
Assets/Development/Animations/GravityLights/GravityLights.controller
Assets/Development/Animations/GravityLights/GravityLights.controller.meta
Assets/Development/Prefabs/Player/Player.prefab
Assets/Development/Scripts/Environment/Events/GravityStorm.cs
Assets/Development/Scripts/Environment/Physics/GravityStation.cs
Assets/Development/Scripts/Helpers/Managers/GameManager.cs
Assets/Development/Scripts/Player/PlayerController.cs
Assets/Scenes/MasterScenes/T5M3_BUILD.unity

Update Gravity Event

---

.idea/.idea.Baristapocalypse/.idea/workspace.xml
Assets/Development/Scripts/UI/NextUIButton.cs
Assets/Scenes/MasterScenes/LobbyScene.unity
Assets/Scenes/MasterScenes/T5M3_BUILD.unity

https://
- 
fixed lobby return to menu button
fixed trash station box collider
remove mop in middle of the scene 
-

Bug fixing

---

Assets/Scenes/MasterScenes/T5M3_BUILD.unity

https://trello.com/c/0T5mQKYa/537-reorganize-ingredient-stations-to-match-player-feedback
- Left to right - Bio, Liquid, Sweet, Bean
- This matches the new order stats UI as well in another PR

Reorganize brewing stations based on feedback

---

Assets/Scenes/MasterScenes/T5M3_BUILD.unity
Assets/Scenes/MasterScenes/T5M3_BUILD/Global Volume Profile.asset
Assets/Scenes/MasterScenes/T5M3_BUILD/Global Volume Profile.asset.meta

Test Lighting

---

Assets/Development/Scripts/Helpers/GameValueHolder.cs

https://
- Default difficulty to "easy"
-

Default difficulty to "easy"

---

Assets/Development/Scripts/UI/OrderStats.cs

https://trello.com/c/VmrpSGSw/526-if-thrown-customer-with-active-order-brewing-station-may-not-release-for-next-customer
- When customer leaves while order is in progress
- When customer is thrown while order is in progress

Fix for orders not resetting in certain conditions

---

Assets/Development/Scripts/AI/CustomerReview.cs

https://trello.com/c/qvjNh17H/559-impossible-to-get-a-5-star-review
- Drink score of 5 stars possible

Possible to get 5 stars

---

Assets/Development/Prefabs/UI/HUD.prefab
Assets/Development/ScriptableObjects/DifficultiesSO/Easy.asset
Assets/Development/ScriptableObjects/DifficultiesSO/Hard.asset
Assets/Development/ScriptableObjects/DifficultiesSO/Medium.asset
Assets/Development/Scripts/AI/CustomerManager.cs
Assets/Development/Scripts/Helpers/Managers/DifficultySO.cs
Assets/Development/Scripts/Helpers/Managers/DifficultySettings.cs

https://trello.com/c/fHa0hDyN/560-shift-over-when-does-win-lose-happen
- Not sure if this fixes all scenarios, but single shift single wave, double shift double wave seems to work
- GameOver screen appears with success / fail conditions

Waves and Shifts Fixes

---

Assets/Development/Prefabs/Enviorment/Messes/messCup.prefab
Assets/Development/Scripts/Player/PlayerController.cs
Assets/Development/Scripts/UI/OrderStats.cs

https://
- Mess Cup Networked
-

Mess Cup Networked

---

Assets/Development/Prefabs/shaders/Shader Graphs_WC MainWall.mat
Assets/Development/Scripts/Camera/MainMenuManager.cs
Assets/Scenes/MasterScenes/MainMenuScene.unity
Assets/Scenes/MasterScenes/T5M3_BUILD.unity

https://
- Appling new button sounds to the main menu
-

Sound adjusting

---

Assets/Development/Animations/Doors.meta
Assets/Development/Animations/Doors/LeftDoor.controller
Assets/Development/Animations/Doors/LeftDoor.controller.meta
Assets/Development/Animations/Doors/LeftDoorCloses.anim
Assets/Development/Animations/Doors/LeftDoorCloses.anim.meta
Assets/Development/Animations/Doors/LeftDoorOpens.anim
Assets/Development/Animations/Doors/LeftDoorOpens.anim.meta
Assets/Development/Animations/Doors/RightDoor.controller
Assets/Development/Animations/Doors/RightDoor.controller.meta
Assets/Development/Animations/Doors/RightDoorCloses.anim
Assets/Development/Animations/Doors/RightDoorCloses.anim.meta
Assets/Development/Animations/Doors/RightDoorOpens.anim
Assets/Development/Animations/Doors/RightDoorOpens.anim.meta
Assets/Development/Prefabs/Enviorment/Maps/Map01.prefab
Assets/Development/Scripts/Camera/MainMenuManager.cs
Assets/Scenes/MasterScenes/MainMenuScene.unity
Assets/Scenes/MasterScenes/T5M3_BUILD.unity

https://
- Added Shop door Animations
-

Added Shop door Animations

---

Assets/Development/Scripts/Camera/MainMenuManager.cs

fix for mainMenuManager.cs error

---

Assets/Development/Scripts/Camera/LookAt.cs
Assets/Development/Scripts/Camera/LookAt.cs.meta
Assets/Scenes/MasterScenes/T5M3_BUILD.unity

Camera updates douglas

---

Assets/Development/Prefabs/Customers/Customer Sample.prefab
Assets/Development/Prefabs/Enviorment/DoorOpener.prefab
Assets/Development/Prefabs/Enviorment/DoorOpener.prefab.meta
Assets/Development/Scripts/Environment/DoorOpener.cs
Assets/Development/Scripts/Environment/DoorOpener.cs.meta
Assets/Development/Scripts/Player/PlayerController.cs
Assets/Scenes/MasterScenes/T5M3_BUILD.unity

https://trello.com/c/jNOnaxRd/584-door-needs-to-open-and-close
- Door opens in the game scene on player and customer enter / exit
- Added kinematic rigid body to customer by default
- Disabled kinematic on pick-up customer
- Only loitering customers can be picked up

Door Opener

---

Assets/Scenes/MasterScenes/T5M3_BUILD.unity

- Door animator refs didn't get pushed after rebase.  Oops
-

Animator refs didn't save

---

Assets/Development/Prefabs/shaders/CircleSync.cs
Assets/Development/Prefabs/shaders/Shader Graphs_WC MainWall.mat
Assets/Development/Prefabs/shaders/Shader metal.mat
Assets/Development/Prefabs/shaders/Shader metal.mat.meta
Assets/Development/Prefabs/shaders/WC metal 1.shadergraph
Assets/Development/Prefabs/shaders/WC metal 1.shadergraph.meta
Assets/Development/Scripts/Player/PlayerController.cs
Assets/Scenes/MasterScenes/T5M3_BUILD.unity
Assets/TextMesh Pro/Examples & Extras/Resources/Fonts & Materials/Bangers SDF.asset

Working on stuff douglas

---

Assets/Development/Prefabs/Stations/Environment/Mop.prefab
Assets/Development/Scripts/AI/CustomerBase.cs
Assets/Development/Scripts/Environment/Messes/Spill.cs
Assets/Development/Scripts/Environment/Stations/BrewingStation.cs
Assets/Development/Scripts/Environment/Stations/TrashStation.cs
Assets/Development/Scripts/Player/Pickup/Pickup.cs
Assets/Development/Scripts/Player/PlayerController.cs

https://
- Player cannot longer throw mop to trash station
- Animation resets after interacting with trash station
- Added RB to mop
- player can repick up mop
- Player creates sill when running with coffee but not throwing the cup
- Delivering Drink is now timed to give the customer the drink
-

Animation Fixes

---

Assets/Development/Scripts/AI/CustomerBase.cs
Assets/Development/Scripts/Helpers/Managers/GameManager.cs
Assets/Development/Scripts/UI/ShiftEvaluationUI.cs

https://
- Events do not trigger during evaluation fix
-

Events do not trigger during evaluation fix

---

Assets/Development/Scripts/UI/ScoreUI.cs

streak text under money jar now showing correctly

---

Assets/Development/Prefabs/Enviorment/Level/BP_stoolfloat.prefab
Assets/Development/Prefabs/shaders/Shader Graphs_WC MainWall.mat
Assets/Scenes/MasterScenes/T5M3_BUILD.unity

Customers now go to actual chair
https://
- 
-

Fixed Prefab for stools

---

Assets/Development/Animations/Animators/PhillipAnimator.controller
Assets/Development/Prefabs/Player/Player.prefab
Assets/Development/Scripts/Player/PlayerController.cs

https://
- Player movement Tweak
- Reduce player speed and increased animations speed
- Corrected player model size
-

Player movement Tweak

---

Assets/Development/Scripts/Environment/Physics/GravityStation.cs

- Mess cups go back to normal after event off
https://
- 
-

Gravity Event Fix

---

Assets/Development/Prefabs/UI/HUD.prefab
Assets/Scenes/MasterScenes/T5M3_BUILD.unity

NA
- Updated tutorial images on Meg's fancy new beautiful UI
- Meg will probably want to put a background behind it at some point for clarity, but the images be back

Tutorial Images on new UI

---

Assets/Development/Scripts/Camera/CameraZoom.meta
Assets/Development/Scripts/Camera/CameraZoom/CameraStation1.cs
Assets/Development/Scripts/Camera/CameraZoom/CameraStation1.cs.meta
Assets/Scenes/MasterScenes/T5M3_BUILD.unity

camera zoom

---

Assets/Scenes/MasterScenes/MainMenuScene.unity

NA
- Red insists on perfection, main menu centered to the pixel

Bumped main menu over to the center of the tunnel

---

Assets/Development/Prefabs/Customers/Customer Sample.prefab
Assets/Development/Scripts/AI/CustomerBase.cs
Assets/Development/Scripts/AI/CustomerRandomizer.cs

Customers animating on client and host now

---

Assets/Development/Prefabs/Customers/Customer Sample.prefab

https://
- added a sphere for customer interaction 
-

Updated Customer prefab to have a sphere

---

Assets/OToon- URP Toon Shading/Unity_2021_2022_upgrade_1.7.0.unitypackage.meta
Assets/Scenes/MasterScenes/T5M3_BUILD.unity

Minigame showing

---

Assets/Development/Scripts/Multiplayer/Lobby/LobbyUI.cs
Assets/Development/Scripts/UI/LevelLoader.cs
Assets/Scenes/MasterScenes/LobbyScene.unity
Assets/Scenes/MasterScenes/MainMenuScene.unity

https://trello.com/c/9hvekfQS/678-add-back-button-to-multiplayer-menu
- Created a button to go back to the main menu after hitting multiplayer
-

Created a button to go back to the mainmenu from lobbyscene

---

Assets/Development/Scripts/AI/CustomerBase.cs
Assets/Development/Scripts/Audio/AudioScripts/AudioClipRefsSO.cs

-If a customer is given a drink when in the leaving state a sound will know play to let the player know they cant do that
https://trello.com/c/9ahONLJj/601-does-it-feel-bad-that-you-cant-give-the-drink-to-the-customer-when-they-are-walking-out
- 
-

Not valid to give drink sound plays

---

Assets/Development/Prefabs/UI/HUD.prefab
Assets/Development/Scripts/Helpers/Managers/GameManager.cs
Assets/Development/Scripts/Helpers/Managers/UIManager.cs

multiplayer pause not working before this
https://
- Created Rpc's to subscribe to pause event, Players were not subscribing
- Fixed resume button to go back to game, 
- Changed children order in HUD prefab to the correct order
-

Multiplayer Pause Fix

---

.idea/.idea.Baristapocalypse/.idea/workspace.xml
Assets/Development/Prefabs/Customers/Customer Sample.prefab
Assets/Development/Prefabs/Enviorment/Messes/Spill.prefab
Assets/Development/ScriptableObjects/DifficultiesSO/Easy.asset
Assets/Development/ScriptableObjects/DifficultiesSO/Hard.asset
Assets/Development/ScriptableObjects/DifficultiesSO/Medium.asset
Assets/Development/Scripts/AI/Base.cs
Assets/Development/Scripts/AI/CustomerBase.cs
Assets/Development/Scripts/Environment/Messes/Spill.cs
Assets/Development/Scripts/Helpers/Managers/DifficultySO.cs
Assets/Development/Scripts/Helpers/Managers/GameManager.cs
Assets/Development/Scripts/Helpers/Managers/GameManager.cs.meta
Assets/Development/Scripts/Player/PlayerController.cs
Assets/Scenes/MasterScenes/T5M3_BUILD.unity

Spills update

---

Assets/Development/Prefabs/Player/Player.prefab
Assets/Development/Scripts/Player/PlayerController.cs

https://
- Updated the spill interaction
-

Updated the spill interaction

---

Assets/Development/Prefabs/Enviorment/Messes/Spill.prefab
Assets/Development/Scripts/Player/PlayerController.cs

(https://trello.com/c/VFI39hA6)
- Update UI Spill minigame size
- changed keyboard interaction to Q
-

Just updated UI size && Made Q to interact

---

Assets/Development/Animations/Transition/SceneTransition_End.anim
Assets/Development/Animations/Transition/SceneTransition_Start.anim

Fixed Scene Transition Bounds

---

Assets/Development/Prefabs/Player/Player.prefab

pickup point in player fix

---

Assets/Scenes/MasterScenes/LobbyScene.unity

Set Charlimit to Lobby Name to 12
Set Charlimit to Join Code to 6
https://trello.com/c/TpxJSeje
- 
-

Lobby Scene Adding Char Limits to Input Fields

---

Assets/Art/CodeMonkeyAssets/_Assets/PrefabsVisuals/PlayerVisual.prefab
Assets/Development/Prefabs/Player/CharacterSelectPrefab.prefab
Assets/Development/Prefabs/Player/Player.prefab
Assets/Development/Scripts/AI/Base.cs
Assets/Development/Scripts/AI/CustomerBase.cs
Assets/Development/Scripts/Environment/Stations/BrewingStation.cs
Assets/Development/Scripts/Environment/Stations/TrashStation.cs
Assets/Development/Scripts/Helpers/Managers/UIManager.cs
Assets/Development/Scripts/Player/PlayerColorChoice.cs
Assets/Development/Scripts/Player/PlayerController.cs
Assets/Development/Scripts/UI/CustomerReviewManager.cs
Assets/Development/Scripts/UI/OrderStats.cs
Assets/Scenes/MasterScenes/CharacterSelectScene.unity

https://
- Fixed null references in player select screen
- Yorp review working again (oops)
- Characters change colors again (not sure if wanted)
- Removed duplicate variable names in trash station and customer
- Money should be synced after player empties brewing station
- Added cooldown to brewing station empty (10 seconds)
-

Networking stuff + brewing station empty sync/cooldown

---

Assets/Art/Materials/PickupPhysics.physicMaterial
Assets/Art/Materials/PickupPhysics.physicMaterial.meta
Assets/Development/Prefabs/Enviorment/Messes/messCup.prefab
Assets/Development/Prefabs/Ingredients/CoffeeCup.prefab
Assets/Development/Prefabs/Player/Player.prefab
Assets/Development/Prefabs/Stations/Environment/Mop.prefab

Added physics Mat & changed mass of Messes

---

Assets/Development/Animations/Animators/PhillipAnimatorFinal.controller
Assets/Development/Animations/FinalPlayerModelAnims/BP_Barista_Cleaning_Vac.anim
Assets/Development/Scripts/Environment/Messes/Spill.cs
Assets/Development/Scripts/Player/PlayerController.cs

https://
- Pick up mop/vac
- Movement with mop/vac
-  Moping Vacuming
-

Mop/Vac Animations

---

Assets/Development/Animations/Animators/PhillipAnimatorFinal.controller
Assets/Development/Animations/FinalPlayerModelAnims/BP_Barista_Slipping.anim
Assets/Development/Scripts/Environment/Messes/Spill.cs
Assets/Development/Scripts/Player/PlayerController.cs

https://
- Player Slip Animation
-

Player Slip Animation

---

Assets/Scenes/MasterScenes/T5M3_BUILD.unity

ui was disabled in recent merge

---

Assets/Development/ScriptableObjects/InputImagesSO/InputImagesSO-DualSense.asset
Assets/Development/ScriptableObjects/InputImagesSO/InputImagesSO-KeyboardMouse.asset
Assets/Development/ScriptableObjects/InputImagesSO/InputImagesSO-Xbox.asset
Assets/Development/Scripts/Camera/MainMenuManager.cs
Assets/Scenes/MasterScenes/MainMenuScene.unity

https://trello.com/c/LdbmtlEe/822-volume-sliders-spacing-on-main-menu-are-too-close
- Fixed options sliders spacing
- Gamepad = null, nothing selected in main menu
NA

Default buttons when gamepad not enabled / Volume sliders

---

Assets/Development/Prefabs/UI/QueueTimerSlider.prefab
Assets/Development/Scripts/Helpers/Managers/OrderManager.cs
Assets/Development/Scripts/Multiplayer/Lobby/ConnectionResponseUI.cs
Assets/Development/Scripts/Multiplayer/Lobby/LobbyManager.cs
Assets/Development/Scripts/Multiplayer/Network/CharacterSelectUI.cs
Assets/Development/Scripts/UI/OrderQueueUI.cs
Assets/Development/Scripts/UI/QueueTimerSlider.cs
Assets/Development/Scripts/UI/QueueTimerSlider.cs.meta
Assets/Scenes/MasterScenes/LobbyScene.unity

Added a connecting/creating lobby screen
Order queue timers should show after a quick scene change
https://
- 
-

Cant create double lobbies anymore

---

Assets/Development/Prefabs/Managers/CustomerManager.prefab
Assets/Development/Prefabs/Stations/Wifi.prefab
Assets/Development/ScriptableObjects/DifficultiesSO/Easy.asset
Assets/Development/ScriptableObjects/DifficultiesSO/Hard.asset
Assets/Development/ScriptableObjects/DifficultiesSO/Medium.asset
Assets/Development/Scripts/AI/CustomerBarFloor.cs
Assets/Development/Scripts/AI/CustomerBase.cs
Assets/Development/Scripts/Environment/CustomerExit.cs
Assets/Development/Scripts/Environment/CustomerExit.cs.meta
Assets/Scenes/MasterScenes/T5M3_BUILD.unity

Added an exit for when no chair is available
Remove Destory Object in customer base and added an ontrigger for the exit instead,(computing Pathing takes time) Fixed Loitering Exit and Entry State
(https://trello.com/c/tIlx7gND)
- Reapplying the lost changes due to pevious merge conflict
- Fixed some problems for the loitering state 
- Loitering needs more testing just incase more bugs spawned
-

Customer Fixes

---

Assets/Development/Scripts/Player/PlayerController.cs

(https://trello.com/c/orsnB6mK)
- Added a check for the player animation
-

Added a check for is animating

---

Assets/Development/Scripts/Helpers/Managers/InputManager.cs
Assets/Development/Scripts/Player/ControllerInputs.cs
Assets/Development/Scripts/Player/ControllerInputs.inputactions
Assets/Development/Scripts/Player/PlayerController.cs

https://trello.com/c/J3wwevqc/796-fix-toggle-between-brewing-stations-make-1-select-left-brewing-station-and-2-select-right-brewing-st
- 1 / 2 and LB / RB select specific instead of cycle through

Independent controls for brewing station select

---

Assets/Development/Prefabs/Managers/CustomerManager.prefab
Assets/Development/Prefabs/Stations/Wifi.prefab
Assets/Development/ScriptableObjects/DifficultiesSO/Easy.asset
Assets/Development/ScriptableObjects/DifficultiesSO/Hard.asset
Assets/Development/ScriptableObjects/DifficultiesSO/Medium.asset
Assets/Development/Scripts/AI/CustomerBarFloor.cs
Assets/Development/Scripts/AI/CustomerBase.cs
Assets/Development/Scripts/Environment/CustomerExit.cs
Assets/Development/Scripts/Environment/CustomerExit.cs.meta
Assets/Scenes/MasterScenes/T5M3_BUILD.unity

Merge fix/customer disappearing&&loitering

---

Assets/Development/Prefabs/Managers/CustomerManager.prefab
Assets/Development/Scripts/AI/CustomerBarFloor.cs
Assets/Development/Scripts/AI/CustomerBase.cs
Assets/Development/Scripts/AI/CustomerExit.cs
Assets/Development/Scripts/AI/CustomerExit.cs.meta

Again
https://
- just redoing the stuff from disapearing customers and loitering bug fixes
-

Reapply Fix customers loitering/disappearing

---

Assets/Development/Animations/Animators/IngredientSelectionController.controller
Assets/Development/Prefabs/Stations/Ingredient/BeanStation.prefab
Assets/Development/Prefabs/Stations/Ingredient/BioMatterStation.prefab
Assets/Development/Prefabs/Stations/Ingredient/LiquidStation.prefab
Assets/Development/Prefabs/Stations/Ingredient/SweetenerStation.prefab
Assets/Scenes/MasterScenes/T5M3_BUILD.unity

Reverts mikestiers/Baristapocalypse#489

Revert "I've got two tickets to paradise"

---

Assets/Development/Prefabs/Stations/Ingredient/SweetenerStation.prefab

sweatner vfx change

---

Assets/Development/Scripts/Player/PlayerController.cs

Player cannot dash if is holding mop or customer

---

Assets/Development/Prefabs/Enviorment/Level/BP_stoolfloat.prefab
Assets/Development/Prefabs/Enviorment/Maps/Map01.prefab
Assets/Development/Prefabs/Managers/CustomerManager.prefab
Assets/Development/ScriptableObjects/DifficultiesSO/Easy.asset
Assets/Development/ScriptableObjects/DifficultiesSO/Hard.asset
Assets/Development/ScriptableObjects/DifficultiesSO/Medium.asset
Assets/Development/Scripts/Environment/BarChairs.cs
Assets/Development/Scripts/Environment/BarChairs.cs.meta
Assets/Scenes/MasterScenes/T5M3_BUILD.unity

(https://trello.com/c/pHCt1j8o)
- changed rotation of customers
- removed the moon over the customer line queue
- added booths to sit again (SCENE CHANGE - i tried to do it in the prefab)
-

Made customers rotate and add booth sits again

---

Assets/Development/Scripts/Player/PlayerController.cs

https://
- Dirty fix for player loosing reference with interactable objects
-

Dirty fix for player loosing reference with interactable objects

---

Assets/Development/Prefabs/Enviorment/Colliders.meta
Assets/Development/Prefabs/Enviorment/Colliders/Colliders in game scene.prefab
Assets/Development/Prefabs/Enviorment/Colliders/Colliders in game scene.prefab.meta
Assets/Scenes/MasterScenes/T5M3_BUILD.unity

fixed and ready

---

Assets/Development/Prefabs/RoombaConsole.prefab
Assets/Development/Scripts/AI/CleanupBot.cs
Assets/Development/Scripts/AI/RoombotConsole.cs
Assets/Scenes/MasterScenes/T5M3_BUILD.unity

https://
- Added Visuals for RoombaConsole
- Added Current State of Roomba in Console
- Added Interactive Button for Console
- Added Standby functionality to not spam Change state of console
-

Added Console Functionality

---

Assets/Development/Scripts/Helpers/GameValueHolder.cs
Assets/Development/Scripts/Helpers/Managers/DifficultySettings.cs
Assets/Development/Scripts/Helpers/SceneHelper.cs

https://trello.com/c/8AnNZT8u
- Added a Reset of Shifts in Restart
-

Added Reset of Shifts in SceneHelper Restart

---

Assets/Art/Textures/Stations/Lines/M_Lines_Beans1.mat
Assets/Art/Textures/Stations/Lines/M_Lines_Beans2.mat
Assets/Art/Textures/Stations/Lines/M_Lines_Beans_Brew1.mat
Assets/Art/Textures/Stations/Lines/M_Lines_Beans_Brew2.mat
Assets/Art/Textures/Stations/Lines/M_Lines_Bio1.mat
Assets/Art/Textures/Stations/Lines/M_Lines_Bio2.mat
Assets/Art/Textures/Stations/Lines/M_Lines_Bio_Brew1.mat
Assets/Art/Textures/Stations/Lines/M_Lines_Bio_Brew2.mat
Assets/Art/Textures/Stations/Lines/M_Lines_Liquid1.mat
Assets/Art/Textures/Stations/Lines/M_Lines_Liquid2.mat
Assets/Art/Textures/Stations/Lines/M_Lines_Liquid_Brew1.mat
Assets/Art/Textures/Stations/Lines/M_Lines_Liquid_Brew2.mat
Assets/Art/Textures/Stations/Lines/M_Lines_Sweet1.mat
Assets/Art/Textures/Stations/Lines/M_Lines_Sweet2.mat
Assets/Art/Textures/Stations/Lines/M_Lines_Sweet_Brew1.mat
Assets/Art/Textures/Stations/Lines/M_Lines_Sweet_Brew2.mat
Assets/OToon- URP Toon Shading/Unity_2021_2022_upgrade_1.7.0.unitypackage.meta
ProjectSettings/DynamicsManager.asset

fixed UVs for VFX

---

Assets/Art/station animations/Samori's animations/Animations/garbadge/garbadgeshutCLOSE.playable
Assets/Art/station animations/Samori's animations/station animation test bed.unity
Assets/Development/Prefabs/Stations/TrashStation.prefab

fixed the closed animation for the garbage prefab
https://
- 
-

fixed garbadge animation

---

Assets/Development/Prefabs/Enviorment/Messes/Spill.prefab
Assets/Development/Prefabs/Player/Player.prefab
Assets/Development/Scripts/Environment/Messes/Spill.cs
Assets/Development/Scripts/Player/PlayerController.cs

https://
- Added Player Acceleration
-

Added Player Acceleration

---

Assets/Development/Scripts/Player/PlayerController.cs
Assets/OToon- URP Toon Shading/Unity_2021_2022_upgrade_1.7.0.unitypackage.meta
Assets/Scenes/MasterScenes/T5M3_BUILD.unity

- No longer able to "wiggle" when in the tutorial and a supervisor message is up
- Supervisor stays out 1 sec longer (3 sec)
- Disabled the ingredients being verbally shown above the brewer
https://
- 
-

A few tweaks

---

Assets/Art/station animations/Samori's animations/updated models/Beans_Rigged -samori up.prefab
Assets/Art/station animations/Samori's animations/updated models/Biomatter_low.prefab
Assets/Development/Prefabs/Stations/BrewingStation 2.prefab
Assets/Development/Prefabs/Stations/BrewingStation.prefab
Assets/Development/Prefabs/Stations/Ingredient/LiquidStation.prefab
Assets/Development/Prefabs/Stations/Ingredient/SweetenerStation.prefab
Assets/Development/Prefabs/Stations/Plate_Beans.prefab
Assets/Development/Prefabs/Stations/Plate_Bio.prefab
Assets/Development/Prefabs/Stations/Plate_Liquids.prefab
Assets/Development/Prefabs/Stations/Plate_Sweet.prefab
Assets/Development/Scripts/Environment/Stations/EmissiveControl.cs
Assets/OToon- URP Toon Shading/Unity_2021_2022_upgrade_1.7.0.unitypackage.meta
Assets/Scenes/MasterScenes/T5M3_BUILD.unity

https://
- can change intensity of each individual emissive
- tubing on the ingredient machines now turn on and off
- UI turned on
-

New emissives set up

---

Assets/Development/Prefabs/Stations/TrashStation.prefab
Assets/Development/Scripts/Environment/Stations/TrashStation.cs

https://trello.com/c/1ya70zuj/828-garbage-chute-animation
- Trash animations for open and close plus triggers
-

Trash animation and triggers

---

Assets/Scenes/MasterScenes/T5M3_BUILD.unity

NA
- Moved trash station out a little bit from the wall because animation started doing a weird clipping thing
-

Trash station animation clipped into the wall

---

Assets/Scenes/MasterScenes/MainMenuScene.unity

NA
- Scripts on ingredient stations not needed in the main menu, causes errors
- Moved the stuff gabe put into the scene last night into an empty game object

Disabled scripts and organized objects

---

Assets/Development/Prefabs/Stations/Ingredient/BeanStation.prefab
Assets/Development/Prefabs/Stations/Ingredient/BioMatterStation.prefab
Assets/Development/Prefabs/Stations/Ingredient/LiquidStation.prefab
Assets/Development/Prefabs/Stations/Ingredient/SweetenerStation.prefab
Assets/Development/Scripts/Environment/Events/RandomEventBase.cs
Assets/Development/Scripts/Environment/Events/WifiEvent.cs
Assets/Development/Scripts/Environment/Events/WifiStation.cs
Assets/Development/Scripts/Helpers/Managers/GameManager.cs
Assets/Development/Scripts/UI/IngredientSelectionUI.cs

For some reason when passing the isWifiEvent.Value is not the proper value for the client. So i just made it a real bool
https://
- 
-

Wifi networked

---

Assets/Development/Prefabs/Stations/Ingredient/BeanStation.prefab
Assets/Development/Prefabs/Stations/Ingredient/BioMatterStation.prefab
Assets/Development/Prefabs/Stations/Ingredient/LiquidStation.prefab
Assets/Development/Prefabs/Stations/Ingredient/SweetenerStation.prefab

https://trello.com/c/WyJoKPXw/858-resort-ingredient-buttons-left-to-right
- Sort ingredient buttons left to right
-

Resorted ingredient buttons left to right

---

Assets/Development/Scripts/VFX/FullScreenEffectController.cs

https://
- Random event FX disabled on game shut down
-

Random event FX disabled on game shut down

---

Assets/Development/Prefabs/Stations/Ingredient/BeanStation.prefab
Assets/Development/Prefabs/Stations/Ingredient/BioMatterStation.prefab
Assets/Development/Prefabs/Stations/Ingredient/LiquidStation.prefab
Assets/Development/Prefabs/Stations/Ingredient/SweetenerStation.prefab
Assets/Development/Scripts/UI/IngredientSelectionUI.cs

https://trello.com/c/xe2PnTST/870-ingredient-station-animations
- Animations on hold until ingredient added
- Random animation selected to play on addingredient()

Ingredient station animations

---

Assets/Scenes/MasterScenes/MainMenuScene.unity

NA
- Turned off scripts in main menu scene that were causing errors / not needed in main menu
- Adjusted cameras to be more centered to the target

Cleared menu errors, adjusted cameras

---

Assets/Art/VFX/Samoris_work/Customer reaction VFX/Paiteince_Loiter.vfx

the loiter affect fixed and in

---

.idea/.idea.Baristapocalypse/.idea/workspace.xml
Assets/Development/Prefabs/Customers/Customer Sample.prefab
Assets/Development/Prefabs/Player/Player.prefab
Assets/Development/Scripts/AI/CustomerBase.cs
Assets/Development/Scripts/AI/CustomerRandomizer.cs
Assets/Development/Scripts/AI/CustomerReactionIndicator.cs
Assets/Development/Scripts/Environment/Events/GravityStorm.cs
Assets/Development/Scripts/Environment/Events/RandomEventBase.cs
Assets/Development/Scripts/Environment/Events/RandomEventEffects.cs
Assets/Development/Scripts/Environment/Events/WifiStation.cs
Assets/Development/Scripts/Player/PlayerColorChoice.cs
Assets/Scenes/MasterScenes/T5M3_BUILD.unity

redid customer FX

---

Assets/Development/Prefabs/Radio/RadioStation.cs
Assets/Scenes/MasterScenes/T5M3_BUILD.unity

added zoom in and out in script for when the event is active
https://
- 
-

Radio station camera Added

---

Assets/Development/Scripts/AI/CustomerBase.cs

forgot some codes when redoing fixes last week

---

Assets/Development/Scripts/Environment/Stations/BrewingStation.cs
Assets/Scenes/MasterScenes/T5M3_BUILD.unity

Brewing stations cameras added

---

.idea/.idea.Baristapocalypse/.idea/workspace.xml
Assets/Art/VFX/Samoris_work/ping effect/Ping Icons/BuldgeControl.cs
Assets/Development/Prefabs/Customers/Customer Sample.prefab
Assets/Development/Prefabs/Player/Player.prefab
Assets/Development/Prefabs/Radio/RadioStation.cs
Assets/Development/Scripts/AI/CustomerBase.cs
Assets/Development/Scripts/AI/CustomerRandomizer.cs
Assets/Development/Scripts/AI/CustomerReactionIndicator.cs
Assets/Development/Scripts/Environment/Events/GravityStorm.cs
Assets/Development/Scripts/Environment/Events/RandomEventBase.cs
Assets/Development/Scripts/Environment/Events/RandomEventEffects.cs
Assets/Development/Scripts/Environment/Events/WifiEvent.cs
Assets/Development/Scripts/Environment/Events/WifiStation.cs
Assets/Development/Scripts/Environment/Stations/BrewingStation.cs
Assets/Development/Scripts/Helpers/Managers/GameManager.cs
Assets/Development/Scripts/Multiplayer/Lobby/LobbyUI.cs
Assets/Development/Scripts/Player/PlayerColorChoice.cs
Assets/Development/Scripts/UI/CustomerReviewManager.cs
Assets/Development/Scripts/UI/GameOverUI.cs
Assets/Development/Scripts/UI/GamePauseUI.cs
Assets/Scenes/MasterScenes/T5M3_BUILD.unity

Multiplayer fixings

---

.idea/.idea.Baristapocalypse/.idea/workspace.xml
Assets/Scenes/MasterScenes/MainMenuScene.unity

reassigned text for fullscreen

---

Assets/Scenes/MasterScenes/CharacterSelectScene.unity

Put in level for character select scene to make it look nicer

---

Assets/Development/Prefabs/Customers/Customer Sample.prefab
Assets/Development/Scripts/AI/CustomerBase.cs
Assets/Development/Scripts/Player/PlayerController.cs

https://
- fixed the cannot pickup any pickups bug
- the customers picked up location and animation synced
- also synced the requirement to pickup the customers
-

Fix/pickup bug&customer pickup animation

---

Assets/Development/Prefabs/Stations/Ingredient/BeanStation.prefab
Assets/Development/Prefabs/Stations/Ingredient/BioMatterStation.prefab
Assets/Development/Prefabs/Stations/Ingredient/LiquidStation.prefab
Assets/Development/Prefabs/Stations/Ingredient/SweetenerStation.prefab
Assets/Scenes/MasterScenes/T5M3_BUILD.unity

NA
- Station animations don't play automatically
- Door field effect

Door effect, ingredient station animations

---

Assets/Development/Prefabs/Enviorment/Messes/messCup.prefab
Assets/Development/Scripts/VFX/NoRotation.cs
Assets/Development/Scripts/VFX/NoRotation.cs.meta

https://
- making the vfx always pointed up regardles of the cup rotation
-

adding script for no rotation for vfx

---

Assets/Development/Prefabs/Stations/BrewingStation 2.prefab

Update coffee cup spawn point on brewing station 2

---

Assets/Development/Prefabs/UI/PingManager.prefab
Assets/Development/Prefabs/UI/PingManager.prefab.meta
Assets/Development/Scripts/UI/PingManager.cs
Assets/Development/Scripts/UI/PingManager.cs.meta
Assets/Scenes/MasterScenes/MainMenuScene.unity

https://
- Just the props for main menu scene
- PingManager (not in use but ready if we want to use it)
-

Main Menu Scene Props

---

Assets/Scenes/MasterScenes/CharacterSelectScene.unity

NA
- Gamepad support for character select
-

Gamepad support for character select

---

Assets/Development/Animations/Doors/LeftDoorCloses.anim
Assets/Development/Animations/Doors/LeftDoorOpens.anim
Assets/Development/ScriptableObjects/AudioClipRefsSO.asset
Assets/Development/Scripts/Audio/AudioScripts/Footstep.cs
Assets/Scenes/MasterScenes/MainMenuScene.unity
Assets/Scenes/MasterScenes/T5M3_BUILD.unity

https://
-Added Footstep.cs to the doors and use animation triggers for door sounds
-

Door Sounds

---

Assets/Art/VFX/Samoris_work/test VFX.unity
Assets/Art/station animations/planet rotation.playable
Assets/Art/station animations/planet rotation.playable.meta

planet and other minor changes

---

Assets/Scenes/MasterScenes/T5M3_BUILD.unity

Vac Instead of Mop

---

Assets/Art/Textures/Stations/Sweet/M_Glass_Sweet.mat
Assets/Development/Prefabs/UI/OrderStats.prefab

Changed order card colors to match stations better

---

Assets/Development/ScriptableObjects/EventsSO/GravityStormSO.asset
Assets/Development/Scripts/Helpers/Managers/TutorialManager.cs

NA
- Gravity glitch more specific
- First ingredient less specific
-

Changed two tutorial messages

---

Assets/Development/Scripts/AI/CustomerBase.cs
Assets/Development/Scripts/Environment/Messes/Spill.cs
Assets/Development/Scripts/Environment/Stations/BrewingStation.cs
Assets/Development/Scripts/Player/PlayerController.cs
Assets/Development/Scripts/UI/IngredientSelectionUI.cs

Added networking to sounds and ingredient station animations
